# Generated by Django 5.0 on 2024-02-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adresse',
            field=models.EmailField(max_length=254),
        ),
    ]
